### ISSUE TITLE
Use existing library for VK

### ISSUE THREAD

**Issue by CyberTailor** [kalinochkind/vkbot#3]
Don't reinvent the wheel! Use the `vk` library, it's very cool.

**Comment by kalinochkind** [comment]
No, thanks. My library has more convenient interface, supports delayed execution, improved error and captcha handling and many other features.

**Comment by kalinochkind** [comment]
Moreover, i could't find how to work with longpoll using that library

**Comment by ghost** [comment]
@kalinochkind longpoll is easy to write yourself
